### ISSUE TITLE
Add Terms and Condition Page

### ISSUE THREAD

**Issue by Angelo-Ufelle** [zuri-training/auth_wiki_team_1_project#110]
terms and condition page from the figma design

**Comment by chiomanwocha** [comment]
To https://github.com/zuri-training/auth_wiki_team_1_project.git
 ! [rejected]        Terms-and-conditions -> Terms-and-conditions (non-fast-forward)
error: failed to push some refs to 'https://github.com/zuri-training/auth_wiki_team_1_project.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


i can't push, i don't know why
